// Code generated by mockery v2.38.0. DO NOT EDIT.

//go:build mocks

package format

import mock "github.com/stretchr/testify/mock"

// MockMessageFooter is an autogenerated mock type for the MessageFooter type
type MockMessageFooter struct {
	mock.Mock
}

type MockMessageFooter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageFooter) EXPECT() *MockMessageFooter_Expecter {
	return &MockMessageFooter_Expecter{mock: &_m.Mock}
}

// Bytes provides a mock function with given fields:
func (_m *MockMessageFooter) Bytes() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bytes")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MockMessageFooter_Bytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bytes'
type MockMessageFooter_Bytes_Call struct {
	*mock.Call
}

// Bytes is a helper method to define mock.On call
func (_e *MockMessageFooter_Expecter) Bytes() *MockMessageFooter_Bytes_Call {
	return &MockMessageFooter_Bytes_Call{Call: _e.mock.On("Bytes")}
}

func (_c *MockMessageFooter_Bytes_Call) Run(run func()) *MockMessageFooter_Bytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageFooter_Bytes_Call) Return(_a0 []byte) *MockMessageFooter_Bytes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageFooter_Bytes_Call) RunAndReturn(run func() []byte) *MockMessageFooter_Bytes_Call {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function with given fields:
func (_m *MockMessageFooter) Len() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockMessageFooter_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockMessageFooter_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockMessageFooter_Expecter) Len() *MockMessageFooter_Len_Call {
	return &MockMessageFooter_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockMessageFooter_Len_Call) Run(run func()) *MockMessageFooter_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageFooter_Len_Call) Return(_a0 int) *MockMessageFooter_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageFooter_Len_Call) RunAndReturn(run func() int) *MockMessageFooter_Len_Call {
	_c.Call.Return(run)
	return _c
}

// SignLen provides a mock function with given fields:
func (_m *MockMessageFooter) SignLen() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SignLen")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockMessageFooter_SignLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignLen'
type MockMessageFooter_SignLen_Call struct {
	*mock.Call
}

// SignLen is a helper method to define mock.On call
func (_e *MockMessageFooter_Expecter) SignLen() *MockMessageFooter_SignLen_Call {
	return &MockMessageFooter_SignLen_Call{Call: _e.mock.On("SignLen")}
}

func (_c *MockMessageFooter_SignLen_Call) Run(run func()) *MockMessageFooter_SignLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageFooter_SignLen_Call) Return(_a0 int) *MockMessageFooter_SignLen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageFooter_SignLen_Call) RunAndReturn(run func() int) *MockMessageFooter_SignLen_Call {
	_c.Call.Return(run)
	return _c
}

// Signature provides a mock function with given fields:
func (_m *MockMessageFooter) Signature() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Signature")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MockMessageFooter_Signature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signature'
type MockMessageFooter_Signature_Call struct {
	*mock.Call
}

// Signature is a helper method to define mock.On call
func (_e *MockMessageFooter_Expecter) Signature() *MockMessageFooter_Signature_Call {
	return &MockMessageFooter_Signature_Call{Call: _e.mock.On("Signature")}
}

func (_c *MockMessageFooter_Signature_Call) Run(run func()) *MockMessageFooter_Signature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageFooter_Signature_Call) Return(_a0 []byte) *MockMessageFooter_Signature_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageFooter_Signature_Call) RunAndReturn(run func() []byte) *MockMessageFooter_Signature_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageFooter creates a new instance of MockMessageFooter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageFooter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageFooter {
	mock := &MockMessageFooter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
