with-expecter: true
filename: "{{.InterfaceName}}_mock.go"
tags: "mocks"
packages:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/model:
    config:
      tags: "mocks"
    interfaces:
      KMSClient:
      KMSClientFactory:
      BaseKeyProvider:
        config:
          mockname: "MockKeyProvider"
          filename: "KeyProvider_mock.go"
      MasterKeyProvider:
      MasterKeyBase:
      MasterKey:
      MasterKeyFactory:
      Key:
        config:
          mockname: "MockKey"
          filename: "Key_mock.go"
      DataKeyI:
        config:
          mockname: "MockDataKey"
          filename: "DataKey_mock.go"
      EncryptedDataKeyI:
        config:
          mockname: "MockEncryptedDataKey"
          filename: "EncryptedDataKey_mock.go"
      CryptoMaterialsManager:
      DecryptionMaterial:
      EncryptionMaterial:
      EncryptionBuffer:
      Wrapper:
      DecryptionHandler:
        config:
          mockname: "MockDecrypter"
          filename: "Decrypter_mock.go"
      EncryptionHandler:
        config:
          mockname: "MockEncrypter"
          filename: "Encrypter_mock.go"
  github.com/chainifynet/aws-encryption-sdk-go/pkg/model/format:
    config:
      tags: "mocks"
    interfaces:
      MessageAAD:
      MessageEDK:
      MessageHeader:
      MessageHeaderAuth:
      MessageBody:
      BodyFrame:
      MessageFooter:
      Deserializer:
      Serializer:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/utils/encryption:
    interfaces:
      GcmBase:
        config:
          mockname: "MockEncrypter"
          filename: "Encrypter_mock.go"
      AEADDecrypter:
      AEADEncrypter:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/utils/rand:
    interfaces:
      RandomGenerator:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/internal/crypto/signature:
    config:
      dir: mocks/{{ replaceAll .PackagePath "internal" "internal_" }}
    interfaces:
      Verifier:
      Signer:
