with-expecter: true
# remove 845 fix when V3 is released
# https://vektra.github.io/mockery/latest/deprecations/#issue-845-fix
issue-845-fix: true
filename: "{{.InterfaceName}}_mock.go"
mock-build-tags: "mocks"
packages:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/model:
    interfaces:
      KMSClient:
      KMSClientFactory:
      BaseKeyProvider:
        config:
          mockname: "MockKeyProvider"
          filename: "KeyProvider_mock.go"
      MasterKeyProvider:
      MasterKeyBase:
      MasterKey:
      MasterKeyFactory:
      Key:
        config:
          mockname: "MockKey"
          filename: "Key_mock.go"
      DataKeyI:
        config:
          mockname: "MockDataKey"
          filename: "DataKey_mock.go"
      EncryptedDataKeyI:
        config:
          mockname: "MockEncryptedDataKey"
          filename: "EncryptedDataKey_mock.go"
      CryptoMaterialsManager:
      DecryptionMaterial:
      EncryptionMaterial:
      EncryptionBuffer:
      Wrapper:
      DecryptionHandler:
        config:
          mockname: "MockDecrypter"
          filename: "Decrypter_mock.go"
      EncryptionHandler:
        config:
          mockname: "MockEncrypter"
          filename: "Encrypter_mock.go"
      GcmCrypter:
      AEADEncrypter:
      AEADDecrypter:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/model/format:
    interfaces:
      MessageAAD:
      MessageEDK:
      MessageHeader:
      MessageHeaderAuth:
      MessageBody:
      BodyFrame:
      MessageFooter:
      Deserializer:
      Serializer:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/internal/utils/rand:
    config:
      dir: mocks/{{ replaceAll .PackagePath "internal" "internal_" }}
    interfaces:
      RandomGenerator:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/internal/crypto/signature:
    config:
      dir: mocks/{{ replaceAll .PackagePath "internal" "internal_" }}
    interfaces:
      Verifier:
      Signer:
  github.com/chainifynet/aws-encryption-sdk-go/pkg/internal/crypto/hasher:
    config:
      dir: mocks/{{ replaceAll .PackagePath "internal" "internal_" }}
    interfaces:
      Hasher:
  hash:
    interfaces:
      Hash:
