// Code generated by mockery v2.38.0. DO NOT EDIT.

//go:build mocks

package signature

import (
	elliptic "crypto/elliptic"

	mock "github.com/stretchr/testify/mock"
)

// MockSigner is an autogenerated mock type for the Signer type
type MockSigner struct {
	mock.Mock
}

type MockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigner) EXPECT() *MockSigner_Expecter {
	return &MockSigner_Expecter{mock: &_m.Mock}
}

// Curve provides a mock function with given fields:
func (_m *MockSigner) Curve() elliptic.Curve {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Curve")
	}

	var r0 elliptic.Curve
	if rf, ok := ret.Get(0).(func() elliptic.Curve); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elliptic.Curve)
		}
	}

	return r0
}

// MockSigner_Curve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Curve'
type MockSigner_Curve_Call struct {
	*mock.Call
}

// Curve is a helper method to define mock.On call
func (_e *MockSigner_Expecter) Curve() *MockSigner_Curve_Call {
	return &MockSigner_Curve_Call{Call: _e.mock.On("Curve")}
}

func (_c *MockSigner_Curve_Call) Run(run func()) *MockSigner_Curve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSigner_Curve_Call) Return(_a0 elliptic.Curve) *MockSigner_Curve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSigner_Curve_Call) RunAndReturn(run func() elliptic.Curve) *MockSigner_Curve_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function with given fields:
func (_m *MockSigner) Sign() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
func (_e *MockSigner_Expecter) Sign() *MockSigner_Sign_Call {
	return &MockSigner_Sign_Call{Call: _e.mock.On("Sign")}
}

func (_c *MockSigner_Sign_Call) Run(run func()) *MockSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSigner_Sign_Call) Return(_a0 []byte, _a1 error) *MockSigner_Sign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSigner_Sign_Call) RunAndReturn(run func() ([]byte, error)) *MockSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Sum provides a mock function with given fields:
func (_m *MockSigner) Sum() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sum")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MockSigner_Sum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sum'
type MockSigner_Sum_Call struct {
	*mock.Call
}

// Sum is a helper method to define mock.On call
func (_e *MockSigner_Expecter) Sum() *MockSigner_Sum_Call {
	return &MockSigner_Sum_Call{Call: _e.mock.On("Sum")}
}

func (_c *MockSigner_Sum_Call) Run(run func()) *MockSigner_Sum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSigner_Sum_Call) Return(_a0 []byte) *MockSigner_Sum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSigner_Sum_Call) RunAndReturn(run func() []byte) *MockSigner_Sum_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *MockSigner) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSigner_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockSigner_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockSigner_Expecter) Write(p interface{}) *MockSigner_Write_Call {
	return &MockSigner_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockSigner_Write_Call) Run(run func(p []byte)) *MockSigner_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockSigner_Write_Call) Return(n int, err error) *MockSigner_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSigner_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockSigner_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSigner creates a new instance of MockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigner {
	mock := &MockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
